default: &default
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default: &default_client
      uri: <%= ENV["MONGO_URI"] %>
      options: &default_options
        # Change the default write concern. (default = { w: 1 })
        write:
          w: :majority
        read:
          mode: :primary_preferred #read preference in a transaction must be primary 
        user: <%= ENV["MONGO_USER"] %>
        password: <%= ENV["MONGO_PASS"] %>
        auth_source: admin

        # Changes the default time in seconds the server monitors refresh their status
        # via ismaster commands. (default: 10)
        heartbeat_frequency: 10

        # The time in seconds for selecting servers for a near read preference. (default: 0.015)
        # local_threshold: 0.015

        # The timeout in seconds for selecting a server for an operation. (default: 30)
        server_selection_timeout: 30

        # The maximum number of connections in the connection pool. (default: 5)
        max_pool_size: 5

        # The minimum number of connections in the connection pool. (default: 1)
        min_pool_size: 1

        # The time to wait, in seconds, in the connection pool for a connection
        # to be checked in before timing out. (default: 5)
        wait_queue_timeout: 15

        # The time to wait to establish a connection before timing out, in seconds.
        # (default: 5)
        connect_timeout: 30

        # The timeout to wait to execute operations on a socket before raising an error.
        # (default: 5)
        socket_timeout: 30

        # Whether to connect to the servers via ssl. (default: false)
        ssl: true

  # Configure Mongoid specific options. (optional)
  options:
    # Includes the root model name in json serialization. (default: false)
    # include_root_in_json: false

    # Include the _type field in serialization. (default: false)
    # include_type_for_serialization: false

    # Preload all models in development, needed when models use
    # inheritance. (default: false)
    # preload_models: false

    # Raise an error when performing a #find and the document is not found.
    # (default: true)
    raise_not_found_error: false

    # Raise an error when defining a scope with the same name as an
    # existing method. (default: false)
    scope_overwrite_exception: true

    # Raise an error when defining a field with the same name as an
    # existing method. (default: false)
    duplicate_fields_exception: true

    # Use Active Support's time zone in conversions. (default: true)
    # use_activesupport_time_zone: true

    # Ensure all times are UTC in the app side. (default: false)
    # use_utc: false

    # Set the Mongoid and Ruby driver log levels when not in a Rails
    # environment. The Mongoid logger will be set to the Rails logger
    # otherwise.(default: :info)
    log_level: :info

    # Control whether `belongs_to` association is required. By default
    # `belongs_to` will trigger a validation error if the association
    # is not present. (default: true)
    # belongs_to_required_by_default: true

    # Application name that is printed to the mongodb logs upon establishing a
    # connection in server versions >= 3.4. Note that the name cannot exceed 128 bytes.
    app_name: HandsOffYoutube